// Curated free-will prompts.
window.WILLS = [
  "Write a letter to yourself from 5 years ago explaining what you wish you'd known.",
  "List every excuse you've used in the last year. Notice which one repeats most.",
  "Write down the story you tell people about yourself, then mark which parts are still true.",
  "Identify three beliefs you hold that you've never actually examined.",
  "Make a list of everyone whose approval you're still chasing, and ask why.",
  "Write the eulogy you'd want at your funeral, then compare it to how you're actually living.",
  "Describe the version of you that your closest friends would defend, then ask if it's accurate.",
  "Name the role you play in your family. Decide if you still want it.",
  "List the times you've abandoned yourself to keep the peace.",
  "Write down what you pretend not to know about your own life.",
  "Empty one drawer completely, then only put back what you'd buy again today.",
  "Delete every app you opened out of boredom this week.",
  "Unsubscribe from 20 email lists in one sitting.",
  "Clean out your wallet or bag — throw away anything expired or forgotten.",
  "Reorganize your phone home screen to reflect who you're becoming, not who you've been.",
  "Donate every piece of clothing that belongs to a past version of you.",
  "Delete photos that keep you anchored to versions of yourself you've outgrown.",
  "Clear your browser bookmarks and only keep what's actively useful.",
  "Throw out all the half-used products promising to fix you.",
  "Wipe down and reset one space in your home that's been quietly stressing you out.",
  "Remove yourself from one commitment that's draining you, today.",
  "Block your own ex (or the ex-shaped person) on every platform.",
  "Turn off all non-human notifications for 24 hours and see what changes.",
  "Take yourself off one mailing list, group, or community you've outgrown.",
  "Make your social media private for a week as an experiment in less performing.",
  "Take a long walk with no podcast, no music, no phone — just notice your thoughts.",
  "Try one form of movement you've never done (a class, a video, dancing alone).",
  "Cook one nourishing meal from scratch, slowly, paying attention.",
  "Sleep without your phone in the room for one night.",
  "Take a cold shower and observe what your mind does to resist it.",
  "Lie on the floor for 20 minutes doing nothing. Notice how hard that is.",
  "Stretch every morning this week, even badly, for 10 minutes.",
  "Eat one meal in complete silence, without screens, without reading.",
  "Walk a route you've never taken in your own neighborhood.",
  "Go to bed two hours earlier than usual, just once, to feel the difference.",
  "Spend an afternoon doing something you loved at age 10.",
  "Write your own bio in third person, as if describing someone you admire.",
  "Introduce yourself to a stranger using only what's true now, not your past credentials.",
  "Dress one day exactly how the future version of you would dress.",
  "Watch a documentary about something completely outside your world.",
  "Spend an afternoon at a library with no agenda.",
  "Draw something — anything — for 30 minutes without judging it.",
  "Cook a recipe from a culture you've never explored.",
  "Write down five questions you want answered before you die, then look up one.",
  "Visit a part of your city you've never been to.",
  "Read a long-form essay from a perspective you usually disagree with.",
  "Teach yourself one practical skill from a YouTube video (knot, knife skill, repair).",
  "Pick a cloud and follow it until it disbands. Mourn it briefly. Find a successor.",
  "Spend an hour believing, with full conviction, that you are undercover as yourself. Behave accordingly. Note what your cover identity does differently.",
  "Get dressed for a genre that doesn't exist yet. Eastern European librarian who moonlights as a sound engineer. Disgraced botanist. Commit fully.",
  "Choose a color you've historically refused to wear and put it on your body in some form today.",
  "Pick a decade and a profession from that decade you'd never actually do (1970s lounge pianist, 1930s aviator) and let it influence one outfit, one playlist, one meal.",
  "Walk through a thrift store and only try on things that scare you slightly. Buy the one that scares you most for under $10.",
  "Build an outfit around a single object you own that has no business being worn out (an opera glove, a strange brooch, your grandfather's watch). Let the room organize around it.",
  "Try a left-handed sketch",
  "Take a bath, lights off",
  "Sit in the sun for ten minutes",
  "Make tea you've been saving",
  "Touch grass. Literally.",
  "Adopt a 24-hour persona, then drop it",
  "Tell a friend exactly what you love about them",
  "Donate a book you've outgrown",
  "Record a voice memo to yourself describing your life right now, to listen to in a year."
];
