// 120 free-will prompts. Pre-generated, kept short and gentle so any one of
// them can fit on a single notebook line.
window.WILLS = [
  "Compliment a stranger",
  "Take a walk without your phone",
  "Call someone you miss",
  "Write a thank-you note by hand",
  "Introduce yourself with a new name today",
  "Sit in silence for five minutes",
  "Reread your favorite poem",
  "Say yes to the next invitation",
  "Say no to one small obligation",
  "Drink a full glass of water",
  "Stretch for two whole minutes",
  "Watch the sunset on purpose",
  "Doodle in the margin of a page",
  "Apologize for something tiny",
  "Forgive yourself for something tiny",
  "Move one piece of furniture to a new room",
  "Sing along, loudly, in the car",
  "Stand outside barefoot",
  "Make eye contact with the moon",
  "Buy a single flower for someone",
  "Leave a 20% bigger tip than usual",
  "Take a one-way bus ride and walk home",
  "Buy something in a color you'd never wear",
  "Write down three small wins",
  "Light a candle for no reason",
  "Get the haircut you've been thinking about",
  "Smile at every dog you see",
  "Memorize a single line of a poem",
  "Donate a book you've outgrown",
  "Eat breakfast at midnight",
  "Wash a window. Just one.",
  "Order the second thing on the menu, not the first",
  "Sit on the floor and stretch",
  "Brush your teeth with the wrong hand",
  "Pick up one piece of litter",
  "Write a postcard to your future self",
  "Try a new route to anywhere",
  "Tell a friend exactly what you love about them",
  "Make a playlist of feelings",
  "Take a nap without guilt",
  "Adopt a 24-hour persona, then drop it",
  "Cancel one thing and don't reschedule",
  "Eat dessert first",
  "Ask a question you usually swallow",
  "Sit somewhere new in a familiar room",
  "Write down a small regret, then tear it up",
  "Compliment your reflection",
  "Open a window and listen for one minute",
  "Pay attention to your own breathing",
  "Whisper a secret to the wind",
  "Quit one small thing today, no apology",
  "Hum your favorite song",
  "Write down a dream you remember",
  "Wear lipstick to do absolutely nothing",
  "Hold a stranger's elevator",
  "Walk in the door singing",
  "Sit by a window and watch the trees",
  "Touch grass. Literally.",
  "Make a wish on the next clock you see",
  "Hug yourself, two whole minutes",
  "Hand-deliver a small kindness",
  "Make tea you've been saving",
  "Write a letter to the 15-year-old you",
  "List ten things that didn't go wrong today",
  "Reach out to someone you ghosted",
  "Order the staff pick at a bookstore",
  "Tell a child something true",
  "Tell an elder something true",
  "Buy yourself the better snack",
  "Walk somewhere and don't take a photo",
  "Pet a friendly animal",
  "Watch clouds for ten minutes",
  "Stop scrolling for one hour",
  "Light incense or a candle and stay with it",
  "Sit on a bench you've never sat on",
  "Wave at a baby on a train",
  "Make eye contact at a checkout and smile",
  "Take yourself on a date you'd take a crush on",
  "Pick a small project and finish it",
  "Take the stairs",
  "Skip the stairs",
  "Look up the etymology of a word you love",
  "Whistle while you do dishes",
  "Sit in the sun for ten minutes",
  "Write down something you're proud of",
  "Wear perfume for no one",
  "Eat slowly enough to taste",
  "Be the one who texts first",
  "Be the one who lets it go",
  "Open a window before you sleep",
  "Spend an hour with no plan, no map",
  "Make your bed like you mean it",
  "Sit on a swing for one minute",
  "Plant something. Anything.",
  "Take a bath, lights off",
  "Notice the first bird you hear",
  "Stop and finish your sentence in your head",
  "Tell someone you're proud of them",
  "Tell yourself you're proud of you",
  "Read one paragraph of philosophy",
  "Watch a black-and-white film",
  "Stretch like a cat in the morning",
  "Skip a line at the grocery store, let someone pass",
  "Buy stamps and use them",
  "Walk in the rain without hurrying",
  "Eat a meal with no screen",
  "Read the credits of a movie",
  "Send a song with no message",
  "Sleep in clean sheets",
  "Write your obituary, then rewrite a paragraph",
  "Try a left-handed sketch",
  "Doodle a small monster on a receipt",
  "Smell a book before you start it",
  "Practice saying a difficult name correctly",
  "Hold the door for three people in a row",
  "Walk past a bakery and go in",
  "Reread an old text from someone kind",
  "Sit at a bar alone and order what you can't pronounce",
  "Hum until you forget what you were worried about",
  "Pick up the phone instead of texting",
  "Say the quiet thing out loud, kindly",
  "Forgive a small thing. Then a slightly bigger one."
];
